config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'tops#index'
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :items do
    resources :clothes_diagnoses
    resources :goods_diagnoses
    resources :book_diagnoses
    resources :other_diagnoses
    resources :flags
  end
  resources :users, only: [:show]
  resources :flags, only: [:index, :create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :clothes_diagnoses, dependent: :destroy
  has_many :goods_diagnoses, dependent: :destroy
  has_many :book_diagnoses, dependent: :destroy
  has_many :other_diagnoses, dependent: :destroy
  has_many :flags, dependent: :destroy

  validates :name, presence: true
  mount_uploader :image, ImageUploader

  enum category: {
    （カテゴリー未選択）: 0,
    衣料品: 1,
    日用品: 2,
    書籍: 3,
    その他: 4
  }

  enum status: {
    （ステータス未選択）: 0,
    まだ捨てない: 1,
    検討中: 2,
    捨てる予定: 3,
    捨てた！: 4
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :access_reject, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
    @items = current_user.items.order(created_at: :DESC).page(params[:page]).per(5)
    @chart = current_user.items.group(:category).count
    @user = current_user
  end

  def show
    @flag = current_user.flags.find_by(item_id: @item.id)
    if @item.category  == "衣料品"
      @clothes_diagnoses = @item.clothes_diagnoses.order(created_at: :desc).limit(1)
      @clothes_diagnosis = @item.clothes_diagnoses.build
    elsif @item.category  == "日用品"
      @goods_diagnoses = @item.goods_diagnoses.order(created_at: :desc).limit(1)
      @goods_diagnosis = @item.goods_diagnoses.build
    elsif @item.category  == "書籍"
      @book_diagnoses = @item.book_diagnoses.order(created_at: :desc).limit(1)
      @book_diagnosis = @item.book_diagnoses.build
    elsif @item.category  == "その他"
      @other_diagnoses = @item.other_diagnoses.order(created_at: :desc).limit(1)
      @other_diagnosis = @item.other_diagnoses.build
    else
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to @item, notice: "登録しました！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: "削除しました！"
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :image,
      :image_cache,
      :comment,
      :category,
      :status
    )
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def access_reject
    redirect_to user_path(current_user.id) if current_user != @item.user
  end

end

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @item.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal">
    <div class="container d-flex flex-column justify-content-center">
      <div class="form-group row">
        <div class="col-3 text-right">
          <%= form.label :name, class: "control-label" %>
        </div>
        <div class="col-7">
          <%= form.text_field :name, class: "form-control", placeholder: "モノ"  %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-3 text-right">
          <%= form.label :image %>
        </div>
        <script type="text/javascript">
          $(function() {
            function readURL(input) {
              if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                  $('#image_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
              }
            }
            $("#item_image").change(function(){
              readURL(this);
            });
          });
        </script>
        <div class="col-7">
          <%= image_tag @item.image.url, id: :image_prev, width: '200' %>
          <%= form.file_field :image, id: :item_image %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-3 text-right">
          <%= form.label :comment, class: "control-label" %>
        </div>
        <div class="col-7">
          <%= form.text_area :comment, class: "form-control", placeholder: "コメント"  %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-3 text-right">
          <%= form.label :category, "カテゴリー", class: "control-label" %>
        </div>
        <div class="col-7">
          <%= form.select :category, Item.categories.keys, class: "form-control" %>（未選択の場合、診断ができません。）
        </div>
      </div>

      <div class="form-group row">
        <div class="col-3 text-right">
          <%= form.label :status, "ステータス", class: "control-label" %>
        </div>
        <div class="col-7">
          <%= form.select :status, Item.statuses.keys, class: "form-control" %>（未選択可）
        </div>
      </div>

      <div class="actions d-flex justify-content-center">
        <% if controller.action_name == "new" %>
          <%= form.submit '登録して診断する' %>
        <% else controller.action_name == "edit" %>
          <%= form.submit '編集を反映する' %>
        <% end %>
      </div>
    </div>

    <div class="mt-3 mb-3 d-flex justify-content-center">
      <%= link_to "モノ一覧画面にもどる", items_path, class: "btn btn-secondary text-white" %>
    </div>

  </form>

<% end %>

app/views/items/edit.html.erb
  <h3 class="ml-5">モノの情報を編集する</h3>
  <%= render 'form' %>

app/views/items/index.html.erb
<div class="container d-flex">
  <div class="row">
    <% if current_user.try(:admin?) %>
      <h3 class ="index-title m-4"><%= @user.name %>のモノ一覧（管理者）</h3>
    <% else %>
      <h3 class ="index-title m-4"><%= @user.name %>のモノ一覧（マイページ）</h3>
    <% end %>

    <%= link_to '断捨離診断する', new_item_path, class: "btn btn-outline-info m-4" %>
    <%= link_to '重要フラグ一覧を見る', flags_path, class: "btn btn-outline-info m-4" %>
    <% if current_user.try(:admin?) %>
      <%= link_to '管理画面', rails_admin_path, class: "btn btn-outline-info m-4" %>
    <% end %>
  </div>
</div>

<div class="d-flex container-fluid table-responsive-sm ">
  <div class="item-content">
    <table class="item-table table table-hover flex-fill bg-light">
      <thead>
        <tr>
          <th>モノ</th>
          <th>カテゴリー</th>
          <th>ステータス</th>
          <th>更新日</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% index = 0 %>
      <% @items.each do |item| %>
        <tr>
          <td id=item-name ><%= item.name %></td>
          <td><%= item.category %></td>
          <td><%= item.status %></td>
          <td><%= item.updated_at.strftime('%Y/%m/%d') %></td>
          <td><%= link_to '詳細を見る / 再診断', item_path(item.id), class: "btn btn-outline-dark" %></td>
          <td><%= link_to '編集', edit_item_path(item.id), class: "btn btn-outline-dark", id: "edit-button#{index}" %></td>
          <td><%= link_to '削除', item, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-outline-dark" %></td>
        </tr>
        <% index += 1 %>
      </tbody>
    <% end %>
    </table>
    <%= paginate @items, theme: 'twitter-bootstrap-4', class: "pagination"%>
  </div>

  <div class="category-chart flex-fill d-inline-block">
    <h4 class="category-title text-center">カテゴリー別グラフ</h4>
    <%= pie_chart @chart %>
  </div>

</div>

app/views/items/new.html.erb
  <h3 class="ml-5">モノの情報を登録する</h3>
  <%= render 'form' %>

app/views/items/show.html.erb
<div class="container d-flex flex-column">
  <h2>モノ詳細 / 診断</h2>

  <div class="d-flex flex-row-reverse">
    <% @item.user_id == current_user.id %>
      <% if @flag.present? %>
      <div class="userpage-item mt-2">
        <%= link_to '重要フラグを解除する', flag_path(id: @flag.id), method: :delete, class: "btn btn-outline-info my-2" %>
      </div>
    <% else %>
      <div class="userpage-item mt-2">
        <%= link_to '重要フラグを立てる', flags_path(item_id: @item.id), method: :post, class: "btn btn-outline-info my-2" %>
      </div>
    <% end %>
  </div>

  <table class="item-content table table-reflow text-center">
    <thead>
      <tr>
        <th>モノ</th>
        <th>写真</th>
        <th>カテゴリー</th>
        <th>ステータス</th>
        <th>コメント</th>
        <th>最終更新日</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody class="alain-item-center">
      <tr>
        <td><%= @item.name %></td>
        <td style="width: 220px;"><%= image_tag @item.image.url %></td>
        <td><%= @item.category %></td>
        <td><%= @item.status %></td>
        <td style="width: 220px;"><%= @item.comment %></td>
        <td><%= @item.updated_at.strftime('%Y/%m/%d') %></td>
        <td><%= link_to '編集', edit_item_path(@item.id), class: "btn btn-outline-dark" %></td>
        <td><%= link_to '削除', @item, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-outline-dark" %></td>
      </tr>
    </tbody>
  </table>

  <h3 class="mt-5 mb-4 text-center">断捨離診断（全5問）</h3>
  <% if @item.category == "衣料品"%>
    <%= render partial: 'clothes_diagnoses/form', locals: { clothes_diagnosis: @clothes_diagnosis, item: @item } %>
    <div id="clothes_diagnoses_area">
      <%= render partial: 'clothes_diagnoses/index', locals: { clothes_diagnoses: @clothes_diagnoses, item: @item } %>
    </div>
  <% elsif @item.category == "日用品"%>
    <%= render partial: 'goods_diagnoses/form', locals: { goods_diagnosis: @goods_diagnosis, item: @item } %>
    <div id="goods_diagnoses_area">
      <%= render partial: 'goods_diagnoses/index', locals: { goods_diagnoses: @goods_diagnoses, item: @item } %>
    </div>
  <% elsif @item.category == "書籍"%>
    <%= render partial: 'book_diagnoses/form', locals: { book_diagnosis: @book_diagnosis, item: @item } %>
    <div id="book_diagnoses_area">
      <%= render partial: 'book_diagnoses/index', locals: { book_diagnoses: @book_diagnoses, item: @item } %>
    </div>
  <% elsif @item.category == "その他"%>
    <%= render partial: 'other_diagnoses/form', locals: { other_diagnosis: @other_diagnosis, item: @item } %>
    <div id="other_diagnoses_area">
      <%= render partial: 'other_diagnoses/index', locals: { other_diagnoses: @other_diagnoses, item: @item } %>
    </div>
  <% else %>
    <p class="alert alert-secondary text-center">診断ができません。カテゴリーを選択してください。</p>
  <% end %>

  <div class="userpage-item my-5">
    <%= link_to "モノの情報を編集する", edit_item_path, class: "btn btn-outline-info mr-3" %>
    <%= link_to "モノ一覧画面にもどる", items_path, class: "btn btn-outline-dark" %>
  </div>

</div>